### ISSUE TITLE
FB_Executorの中断完了が正しく取得できない

### ISSUE THREAD

**Issue by makitagawa243** [Beckhoff-JP/PLC_JobManagementFramework#1]
FB_Executor.abort()を実行し、中断の完了で次動作を行うため戻り値を監視したいのですが、
abort()をコールした後にexecute()をコールするまで_abortingがONしないため
初回のabort()コール時は必ずTRUEが返ってきます。

```
IF _state = E_FutureExecutionState.init OR
   _state = E_FutureExecutionState.process OR
   _state = E_FutureExecutionState.quit THEN
	_abort := TRUE;	
END_IF

IF 	_abort THEN
	abort := NOT _aborting;
ELSE
	abort := TRUE;
END_IF
```

次サイクル以降はabortの完了状態に応じた値になりますが、1サイクルは必ず無条件でabort() = TRUEになります。

```
IF _state = E_FutureExecutionState.init OR
   _state = E_FutureExecutionState.process OR
   _state = E_FutureExecutionState.quit THEN
	_abort := TRUE;	
END_IF

IF 	_abort THEN
	abort := _state = E_FutureExecutionState.abort AND NOT _aborting;
ELSE
	abort := TRUE;
END_IF
```
戻り値の条件に現在状態がabortであることを加えれば解決するように思います。

**Comment by makitagawa243** [comment]
FB_Executor._abortがexecute()内で毎サイクルFALSEにリセットされるのも影響がありそうです。
execute()/abort()共にサイクル毎呼び出しが前提ですが、
```
fbExecutor.execute();
fbExecutor.abort();
```
のように上位で記述していると
2サイクル目のabort()では E_FutureExecutionState.abortに遷移しているが_abort=FALSEのため
abort()はTRUEになります。

**Comment by makitagawa243** [comment]
execute()側は_abortを状態遷移のトリガーとして利用しているため、abort()メソッド側で状態を考慮して
```
IF _state = E_FutureExecutionState.init OR
   _state = E_FutureExecutionState.process OR
   _state = E_FutureExecutionState.quit THEN
	_abort := TRUE;	
END_IF

IF 	_abort AND _state = E_FutureExecutionState.abort THEN
	abort := NOT _aborting;
ELSE
	abort := TRUE;
END_IF
```
とすると意図通り動作しました。

**Comment by ta-ichihashi** [comment]
修正レポートありがとうございます。abort状態には、外発的要因（abort()メソッド呼び出し）と、内発的要因（init(), execute(), quit()何れかがnErrorIDが0以外の状態で終了した）によって遷移し、_future.abort()を実行し続けますので、子要素に伝搬して停止モードを反映させます。親が内発的要因でabort状態になっても、子要素は外発的要因でabort状態に遷移する感じですね。
自分で作っておきながらこの仕組みすら忘れてしまっていました。
