### ISSUE TITLE
ジョブの一覧を取得するオブザーバ用インターフェース追加

### ISSUE THREAD

**Issue by ta-ichihashi** [Beckhoff-JP/PLC_JobManagementFramework#13]
# 概要

構築したジョブモデルをレポートする機能。（HMIへジョブ構成を描画するための機能）
ジョブコンテナにイテレーションメソッドを実装し、トップのFB_Executorから再帰的にイテレータを通して登録したオブザーバメソッドを呼び出すファンクションブロックと、オブザーバインターフェースを追加する。

# 実装

## ジョブコンテナにイテレータを追加

InterfaceContainerのインターフェースに二つのメソッドを追加し、全ジョブコンテナに格納されたFB_ExecutorへのREFERENCEを順次取り出せるイテレータ機能を追加。

* `_index_generator_`

   コンテナに格納しているジョブが格納された配列のインデックス（1以上）を返すイテレータ。これまでFB_QueueJobContainer,FB_ParallelQueueJobContainer に実装していた `_future_generator` という名前のメソッドは廃止し、こちらへ変更。引数は無しで、0を返した際にイテレーションの終了を通知する仕様へ変更。

* `each_executor`

   `_index_generator_`を使って、FB_ExecutorへのREFERENCEを返すメソッド。こちらもイテレータとして機能する。終了時は0へのREFERENCEが返るため、__ISVALIDREF()にて終了を判別することができる。

## `FB_ExecutorTreeSearch` ファンクションブロックの追加

事前に `InterfaceObserver` の `subscribe_job_directory` を実装したファンクションブロックを `subscriber` として登録しておき、最上位のExecutorオブジェクトをsearch() メソッドの引数に渡して実行すると、子要素対して再帰的にFB_Executorを検索し、 `subscribe_job_directory` メソッドを実行する。

## `InterfaceEventReporter` から `InterfaceObserver` への変更

`InterfaceEventReporter` から `InterfaceObserver`  改名し、`report` メソッドを、`subscribe_job_event` メソッドへ改名。加えて `subscribe_job_directory` メソッドを追加した。

`InterfaceEventReporter` のインターフェースを、ジョブフレームワークのさまざまなオブザーバオブジェクトとして機能集約するため、汎用的な名前である  `InterfaceObserver` に改名した。また、このメソッドの命名規則として `subscribe_****` とすることとした。これに併せて、`report` メソッドは `subscribe_job_event` とし、レポーティング以外の目的にも沿うものとする。

# サンプル

フレームワークのMAINプログラムには、以下のサンプルを掲載。

``` pascal
VAR
    executor: FB_Executor; // main Executor
    fbObserver : FB_observer;
    fbJobTreeSearch : FB_ExecutorTreeSearch;
END_VAR

CASE _state OF

0:
    executor.id := 'MAIN JOB';
    executor.create_container(ContainerType.BATCH, 'Batch Container');
    :
    // <executorにジョブを構築するブロック>
    :
    // Report 'executor' job directory
    fbJobTreeSearch.subscriber := fbObserver;
    fbJobTreeSearch.search(executor);
		
    _state := 1;
1:
    :
```

また、fbObserverのsubscribe_job_directoryメソッドは以下の通り実装。

``` pascal
METHOD subscribe_job_directory : BOOL
VAR_INPUT
    executor    : REFERENCE TO FB_Executor;
END_VAR
VAR
    job_log     : STRING;
END_VAR

job_log := CONCAT(job_log, 'JOB STRUCTURE');
IF executor.future <> 0 THEN
    job_log := CONCAT(job_log, '/ FUTURE_NAME : ');
    job_log := CONCAT(job_log, executor.future.future_name);
    job_log := CONCAT(job_log, ', ');	
END_IF
job_log := CONCAT(job_log, 'JOB_ID : ');
job_log := CONCAT(job_log, executor.id);

ADSLOGSTR(msgCtrlMask := ADSLOG_MSGTYPE_LOG, msgFmtStr := job_log, strArg := '');
```

この実行結果として、次のとおりADSログへジョブの構成が一覧される。

```
Severity	Code	Description	Project	File	Line	Suppression State
Message		2024/08/30 16:33:57 607 ms | 'PlcTask' (350): JOB STRUCTURE/ FUTURE_NAME : Parallel Container, JOB_ID : MAIN JOB/1				
Message		2024/08/30 16:33:57 607 ms | 'PlcTask' (350): JOB STRUCTURE/ FUTURE_NAME : Dynamic parallel tasks, JOB_ID : MAIN JOB/2				
Message		2024/08/30 16:33:57 607 ms | 'PlcTask' (350): JOB STRUCTURE/ FUTURE_NAME : Dynamic job : Counter5, JOB_ID : MAIN JOB/2/5				
Message		2024/08/30 16:33:57 607 ms | 'PlcTask' (350): JOB STRUCTURE/ FUTURE_NAME : Dynamic job : Counter4, JOB_ID : MAIN JOB/2/4				
Message		2024/08/30 16:33:57 607 ms | 'PlcTask' (350): JOB STRUCTURE/ FUTURE_NAME : Dynamic job : Counter3, JOB_ID : MAIN JOB/2/3				
Message		2024/08/30 16:33:57 607 ms | 'PlcTask' (350): JOB STRUCTURE/ FUTURE_NAME : Dynamic job : Count-2, JOB_ID : MAIN JOB/2/2				
Message		2024/08/30 16:33:57 607 ms | 'PlcTask' (350): JOB STRUCTURE/ FUTURE_NAME : Dynamic job : Count-1, JOB_ID : MAIN JOB/2/1				
Message		2024/08/30 16:33:57 607 ms | 'PlcTask' (350): JOB STRUCTURE/ FUTURE_NAME : Button 4 count, JOB_ID : MAIN JOB/1/4				
Message		2024/08/30 16:33:57 607 ms | 'PlcTask' (350): JOB STRUCTURE/ FUTURE_NAME : Button 3 count, JOB_ID : MAIN JOB/1/3				
Message		2024/08/30 16:33:57 607 ms | 'PlcTask' (350): JOB STRUCTURE/ FUTURE_NAME : Button 2 blink, JOB_ID : MAIN JOB/1/2				
Message		2024/08/30 16:33:57 607 ms | 'PlcTask' (350): JOB STRUCTURE/ FUTURE_NAME : Button 1 blink, JOB_ID : MAIN JOB/1/1				
Message		2024/08/30 16:33:57 607 ms | 'PlcTask' (350): JOB STRUCTURE/ FUTURE_NAME : Batch Container, JOB_ID : MAIN JOB			
```

**Comment by masudako** [comment]
いつもお世話になります。

ソースコード、Cloneして拝見させて頂きました。
使用感としては、
　■InterfaceObserverを継承したFBを作成する。
　■subscribe_job_directoryのメソッドにツリー解析時の動作をユーザが実装する
　■FB_ExecuterTreeSearchのプロパティ「subscriber」にInterfaceObserver継承FBを紐づける
　■あとは好きなタイミングで、FB_ExecuterTreeSearch.searchメソッドを実行
という形で相違ありませんでしょうか？

あと、コードを見た感じでは、ツリーに23個のexecutorがぶら下がっている場合、
「subscribe_job_directory」メソッドは23回実行される形の仕様であると思えます。

このあたり、23個のexecutorをサーチし終えた後に、「subscribe_job_directory」メソッドのInputとして
executor配列、もしくは配列の先頭ポインタの形で参照できるようにして、
「subscribe_job_directory」メソッドの実行を１サーチ１回で抑えた方が、
ユーザ側としては使い勝手が良いのでは？という風にも感じました。
（素人考えかもしれませんが・・・。）

本件、またどこかでご意見をお聞かせ頂ければ嬉しく思います。
よろしくお願いいたします。

**Comment by ta-ichihashi** [comment]
投稿ありがとうございます。

> 使用感としては、
> 　■InterfaceObserverを継承したFBを作成する。
> 　■subscribe_job_directoryのメソッドにツリー解析時の動作をユーザが実装する
> 　■FB_ExecuterTreeSearchのプロパティ「subscriber」にInterfaceObserver継承FBを紐づける
> 　■あとは好きなタイミングで、FB_ExecuterTreeSearch.searchメソッドを実行
> という形で相違ありませんでしょうか？

その通りです。

> このあたり、23個のexecutorをサーチし終えた後に、「subscribe_job_directory」メソッドのInputとして
> executor配列、もしくは配列の先頭ポインタの形で参照できるようにして、
> 「subscribe_job_directory」メソッドの実行を１サーチ１回で抑えた方が、
> ユーザ側としては使い勝手が良いのでは？という風にも感じました。

ジョブツリーは何階層にも至り、それぞれの階層で存在するジョブ数も一意には決まりません。コンテナ毎に1回でまとめた配列として引き渡したとしても、ユーザは階層ごとにそのサイズを意識した実装が強制されるため、むしろ使い勝手が悪いと考えたのですがいかがでしょうか。

また、Queue系のジョブはその時々の状況により格納されているジョブのサイズも変動します。コールされるたびにライブラリのサービス側で配列を生成するのは演算負荷はそれなりに高いのであまりやりたくありません。配列として使いたい場合は、ユーザ側で対応いただく方が良いかと思います。

このため、ライブラリサービスとしてはイテレータを提供する事にしました。

イテレータを用いたデザインパターンは、ほぼ定型的に次の通りとなります。FB_ExecuterTreeSearch の searchメソッドも同じパターンで対応しております。

``` pascal
REPEAT
    executor REF= each_executor();  // ここでイテレータコール。0リファレンスが戻ったら終了。
    IF __ISVALIDREF(executor) THEN
        (*
           executorを使った処理。ここでいったん配列に順次格納し、あとから配列アクセスする方法でも構わない。
        *)
    END_IF
UNTIL
    NOT __ISVALIDREF(executor) 
END_REPEAT
```

**Comment by masudako** [comment]
> ジョブツリーは何階層にも至り、それぞれの階層で存在するジョブ数も一意には決まりません。コンテナ毎に1回でまとめた配列として引き渡したとしても、ユーザは階層ごとにそのサイズを意識した実装が強制されるため、むしろ使い勝手が悪いと考えたのですがいかがでしょうか。

ご指摘の通りであると思います。ユーザ側の責任として配列確保など、準備を行う思想である事、理解できました。

> このため、ライブラリサービスとしてはイテレータを提供する事にしました。

上記に関しては、「subscribe_job_directory」にて、配列格納処理などを行うときに、イテレータを活用すれば良い、という
意図でしょうか？であれば、このあたりいまいち腹落ちしていないので、どこかで御相談に乗って頂きたく思います。

「subscribe_job_directory」を拝見する限りでは、ツリーにぶら下がるすべてのexecuterをスキャンするまで、
メソッドを繰り返し実行していく仕様に見えます。本用途であれば、ユーザ側で配列格納を行う場合は
適当な配列カウンタ変数を用意して、「subscribe_job_directory」が実行される都度
　■引数のexecuterをREFERENCE TO FB_Executorの配列に格納
　■カウンタをインクリメント
を繰り返していけば、全ツリー要素の参照にアクセスできる気がするので、
ユーザとしてイテレータを意識する必要な無さそうに思えます。

よろしくお願いいたします。

**Comment by ta-ichihashi** [comment]
> 上記に関しては、「subscribe_job_directory」にて、配列格納処理などを行うときに、イテレータを活用すれば良い、という
> 意図でしょうか？

イテレータは、今回ご用意した`FB_ExecutorTreeSearch` の機構を使わずに、直接ジョブツリーにアクセスして、全要素を配列に直接吐き出したい場合に必要、という意味で使わせていただきました。そういった意図が無い限りイテレータを使う必要はありません。

`FB_ExecutorTreeSearch`  に再帰的にジョブツリーを検索し、コンテナに実装されたイテレータを使ってFB_Executorを取り出す実装がすでに行われていますので、これを使った方法についてご説明します。

仰る通り、一旦すべてを配列に吐き出して、それをユーザが使用する、というアプローチも可能ですが、それでは柔軟性がなくなります。

例えば、`current_state` が `E_FutureExecutionState.abort` のものだけ抽出したい場合、まずライブラリがいったん全ジョブツリーを配列に展開し、そのあと、ユーザがその配列を検索して必要なものだけフィルタして取り出す必要があります。二度の処理手間が発生しています。

しかし、オブザーバメソッドで再帰検索中にフィルタし、例えば平坦な一次元配列などなんでもよいのですが、データの使用用途に併せて最適なデータ構造に格納すれば、二度の処理は必要なくなります。

また、必ずしも用途によっては配列に格納する必要はなく、MQTTで通知したり、CSVファイルに書き出したり、データベースに記録したり、といったことが考えられ、PLC内部でデータを活用するのに適した「配列」というデータモデルにこだわる必要はありません。

このように、配列に全部吐き出してからユーザに渡すのではなく、再帰検索中の「データの流れ」をユーザに公開する手法を[オブザーバパターン](https://ja.wikipedia.org/wiki/Observer_%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3)と呼んでいます。

オブザーバパターンは近年さまざまなフレームワークで用いられています。最も有名なのは、.NET発祥の Reactive Extensions （略して Rx）もその一つです。
