### ISSUE TITLE
コンテナ下のジョブがabortとなった場合に中断、再開を無限ループしてしまう問題

### ISSUE THREAD

**Issue by ta-ichihashi** [Beckhoff-JP/PLC_JobManagementFramework#14]
現在、ジョブコンテナにはabort状態からの再開を指示する実装が欠落している。このため、暫定的にabort状態になったら無条件でコンテナ下のジョブ全てに対してstart()を実行する実装となっている。

例） BatchJobContainerのexecute()の一部
``` pascal
IF _executors[current_executing_future_id]^.current_state = E_FutureExecutionState.abort THEN
	_executors[current_executing_future_id]^.start();
END_IF
```

これにより、上位のコンテナがexecute()のままで、その下のFB_Executeが異常終了したなどで個別にabort状態になった場合、abort()による子オブジェクトの自発的中断、上位からstart()による再開指示が無限に繰り返されてしまう問題となる。

このことは、子オブジェクトがabort()となった場合、上位のジョブツリーに対して停止状態を伝搬させる機構を新たに検討する必要があることを意味している。

#13 で実装したイテレータを用いて親のジョブコンテナを遡って検索し、停止する伝搬範囲を決定して停止処置を行う機構を新たに検討する。

**Comment by ta-ichihashi** [comment]
ただ、これは仕様決めが難しい課題。個々のジョブ、そしてnErrorID毎に個別の停止レベルを定義し、これに応じて停止範囲を決定する必要がある。つまり、エラーの定義とその都度の停止範囲をどのように定義してもらうか、が難しい。機能単位なのか、物理的なモジュールの範囲なのか。はたまた、その時に応じた条件定義によりけりなのか。
また、停止させたあとは再開機構が必要。シナリオとしては単なる再開だけではなく、キャンセル（ジョブそのものを破棄して、無かったものにする）や、退避（あるポイントから別のジョブツリーに付け替える）という処理も考えられる。

**Comment by masudako** [comment]
お世話になります。

> ただ、これは仕様決めが難しい課題。個々のジョブ、そしてnErrorID毎に個別の停止レベルを定義し、これに応じて停止範囲を決定する必要がある。

生産技術者としての感覚ですが、下記３種類の停止選択が出来れば、実用的には問題なさそうに思えます。
① Abort入力が属するツリーの全てのアイテムを停止
② Abort入力がされたコンテナにぶら下がるアイテムを全て停止
③ Abortが入力された対象ジョブ/コンテナのみの停止

①はエア元圧ダウンや非常停止などの緊急処理のイメージ。
②に関しては、複数ＳＴが並列動作するような設備の１ＳＴを停止させるイメージ。
③に関しては、フローの再開可能な一時停止処理を行うようなイメージ、ですかね・・・。

ただ、対象のジョブ/コンテナに対して、①～③の停止処理が全て必要となる可能性は高いと思います。
一つの選択肢としては、現在Abortを１つのメソッドとして定義しているのを
レベル毎に３つのメソッドに分割し、それぞれの停止レベルに別の処理、および別ErrorIDを振れるようにする、
という方法が考えられるか、とは感じます。

**Comment by ta-ichihashi** [comment]
必ずしも物理モジュールで閉じた構成でジョブコンテナが構成されるとも限りません。たとえば2搬送モジュール間でワークの受け渡しを行う場合、ディスパッチにより相互の搬送モジュールに並行ジョブが組まれると思います。この実行時に、互いのハンドが接近している間は両方停止させるべきですが、受け渡し後に離れていっている場合は停止させたくないケースもあるかと思います。

```
接近中    エラー         搬送可
---||--------|/|---+--------<>
戻り中               |
---||-------------+
```

ラダーならメモリ空間があいまいですからこんな実装よくやるのですが、この条件設定が外部からできる必要はあるかもしれませんね。

現状、 `InterfaceObserver` の `subscribe_job_event` を実装することで、全ジョブの状態遷移を監視することは可能です。ここにユーザ独自に停止処理を実装できる仕組みを提供する必要があるかもしれませんね。そのためには次の機能要件が必要だと思います。

* ジョブ定義時に一意のジョブパスが明確であること。
* ジョブパスを通じて停止対象を定義できること。
* ジョブパスを基に対象のFB_Executorを抽出するクエリを実装する必要があること。
* クエリに基づいてabort()処理を伝搬させること。

**Comment by ta-ichihashi** [comment]
私もここまで書いて気付いたのですが、過去の装置システム設計の経験を思い出すと、リソースマネージャ的な機構が必要かもしれません。abort()の伝搬だけでなく、リソースの競合によるインターロックなどを設ける仕組みが必要だと思いました。実行中の全ジョブを監視し続けて、以下の以下の条件を制御するものです。

* Jobのスタート条件

   Jobのスタートが可能であれば `wait_for_process` から `process` へ移行する（start()実行条件）

* Jobの続行条件

   `process` 状態のJOBに対して続行不可能であればabort()を発行する

たとえばParallelQueueJobは、MESからの差立により生成されるJOBとして用意しましたが、全モジュールがいつでも実行可能なわけではありません。最低限物理的な競合が発生しない条件において子ジョブがスタートできるようにするための機構として必要です。また、自動連続動作ではなく、手動での個別動作を行う場合もスタートしてよいかどうか、他のリソースの状態（位置関係）などでジョブ発行してよいかどうかをチェックする機構が必要です。

ジョブだけではなく、リソースも抽象化してこれを通してabort()するのが良いのでしょうかね。

**Comment by masudako** [comment]
Jobのスタート条件、Jobの続行条件に関してそれぞれインタロックを設ける仕組みが必要、というのは私も感じます。
現行のジョブフレームワークを活用して、エア、ロボシリンダを組み合わせた簡単な試作機を組もうと試みているのですが、
【Jobのスタート条件】init()メソッドの冒頭にインタロック条件を記載して、ErrorId発行
【Jobの続行条件】execute()メソッド内にインタロック条件を記載して、ErrorId発行
とするしか無いかと考えておりました。

・・・ですが、この実装方法だと、各デバイスのBody毎に個別のジョブFBを実装しなければならず、
FB数がどえらい事になってしまうと思い、何とかデバイスのBodyと、インタロック条件を切り分けて掛けないかと
試行錯誤しておりました。

本件、どこかで御相談に乗って頂ければ嬉しく思っております。
どのような実装方法にしてもスマートにいかず、思い悩んでいたところでした。

**Comment by ta-ichihashi** [comment]
ちょっと思いつきました。
* インターロックの基本モデルとなるインターフェースを定義。
* インターロックインターフェースにイベント監視の関数を実装。
* Future毎に、1) 処理開始時、2）常時、の2種類で、実装したインターロックオブジェクトをコレクションとして複数登録できるようにする。
* FB_Executorは、process移行前に1)のインターロックコレクションの監視メソッドを実行してインターロック条件検出すればwait_for_processのまま維持。ジョブ実行中は常時2)のコレクションの監視メソッドを実行し、インターロック条件検出すれば、abort()を実行する。

**Comment by ta-ichihashi** [comment]
これとは別に、解除と再開方法を定義しないとダメですね。インターロックインターフェースに停止状態のジョブのポインタをコレクションとして登録できるようにして、一括して再開操作できるようにすればいいですかね。停止状態のジョブが存在したとき、インターロックオブジェクト毎にEventLoggerでアラーム出力できるようにすればいいと思います。
